# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-13 05:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_model_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_model',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.User_Model'),
        ),
    ]
