# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-13 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20170713_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_model',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
